--- 
avatar: "https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png"
baseurl: ""
description: Teacher
disqus: ~
exclude: 
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
footer-links: 
  email: ~
  facebook: ~
  flickr: "https://www.flickr.com/photos/127740096@N02/"
  github: ~
  instagram: ~
  linkedin: ~
  pinterest: ~
  rss: ~
  twitter: ~
gems: 
  - jekyll-sitemap
google_analytics: ~
highlighter: pygments
markdown: redcarpet
name: "testy westy"
permalink: "/:title/"
prose: 
  media: media
  metadata: 
    _posts: 
      - 
        field: 
          element: hidden
          value: blog
        name: category
      - 
        field: 
          element: hidden
          value: blog
        name: layout
      - 
        field: 
          element: text
          label: Title
          value: ""
        name: title
      - 
        field: 
          element: text
          label: "Splash image"
          value: ""
        name: splash
      - 
        field: 
          element: multiselect
          label: "Add Tags"
          options: 
            - 
              name: Apples
              value: apples
            - 
              name: Bananas
              value: bananas
            - 
              name: Pears
              value: pears
            - 
              name: Mangos
              value: mangos
          placeholder: "Choose Tags"
        name: tags
  relativeLinks: "http://sewright.github.io/links.jsonp"
  rooturl: _posts
  siteurl: "http://sewright.github.io/"
sass: 
  style: !ruby/symbol expanded
url: "http://sewright.github.io/"
version: v1.1.0
